### ISSUE TITLE
Why would you open source?

### ISSUE THREAD

**Issue by PrinceFroggy** [ongov/OpenVerify#1]
isn’t that leaving a vulnerability to hackers to reverse the decryption and encrypt their own strings to make a QR code?

Anyone can use: https://github.com/EiNSTeiN-/chosen-plaintext

**Comment by PrinceFroggy** [comment]
> > Why would you open source?
> 
> Many reasons, one of the best being so the public can verify their government isn’t making an app that is doing shady things.
> 
> “Health passports” (for vaccine verification or other purposes) have the potential to carry very negative consequences. At first glance there seems to be no evidence of the potential for logging of identifiable data about the user (businesses) that could be used to log the whereabouts and activities of those being scanned (patrons of businesses).
> 
> We’ll done @ongov!

Oh that’s common knowledge… :P

I still believe by open sourcing they are opening a can of worms for attacks.

When I got time from my busy schedule I will attempt to create an exploit.

**Comment by SilverMarten** [comment]
>When I got time from my busy schedule I will attempt to create an exploit.

Lol. I'm here to have a look at whether there are any vulnerabilities too. That right there is why open source works. If one of us can find a flaw, we can point it out. "Many hands make light work."

As for the `verifyRulesetON.json`... I could see the potential for intercepting it and modifying the `publicKeys` to insert your own; but that would require the target app to be running in online mode (likely) and the attacker to have the ability to intercept their https request and modify it (unlikely).

I'm particularly curious what data can be collected from the QR code by a secondary app. My concern is that people may not realise how easy it is for a program to read their code and log the data somewhere.

**Comment by gabrielgrant** [comment]
> I still believe by open sourcing they are opening a can of worms for attacks.

The widely-held view (consensus?) in the software community is precisely the opposite: “given enough eyeballs, all bugs are shallow” (known as "Linus’s law", [studies seem to confirm it empirically](https://arxiv.org/pdf/2007.10912.pdf) )

In order for any issues to be addressed, though, there does need to be time for the code to be reviewed, tested, and (potentially) fixed. So it would have been nice if the development would have been done in the open, rather than the code being "thrown over the wall" after the app was published. But having the code available now is certainly better than not at all, so we can all look  for, report and fix any remaining issues (as it sounds like you're going to try to do!)
